services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Sandronimus\RestToolsBundle\Action\IndexAction:

    Sandronimus\RestToolsBundle\Action\NewAction:
